### ISSUE TITLE
Pre-Install-Check: Update for System Requirements based on Documentation

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#79]
Consult the latest documentation to update the report generated by the pre-install check tool.

**Comment by kevinlinglesas** [comment]
When this issue is addressed, in an upcoming release, the pre_install_report/viya_cluster_settings.properties file has been replaced by the pre_install_report/viya_deployment_settings.ini file. After you pull down or install the latest code, ensure that the viya_deployment_settings.ini is present and use it to alter any settings. Any viya_cluster_settings.properties files are considered obsolete.

The changes are based on a review and alignment with [SAS documentation](http://pubshelpcenter.unx.sas.com:8080/test/doc/en/itopscdc/v_011/itopssr/n1ika6zxghgsoqn1mq4bck9dx695.htm).

NOTE WELL: A pull of the latest code into an existing local workspace will result in the obsolete .properties file being removed.

**Comment by kevinlinglesas** [comment]
Addressed by [release 1.5.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.5.0)
